name: city_picker_example
description: Demo for how to use the city_pickers plugin.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_city_picker:
    path: ../
  provider: ^6.0.3
  dio: ^4.0.6
  flutter_colorpicker: ^1.0.3
  lpinyin: ^2.0.3

flutter:

  uses-material-design: true
