name: city_picker_example
description: Demonstrates how to use the city_pickers plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_city_picker:
    path: ../
  provider: ^6.0.1
  flutter_colorpicker: ^0.6.0

flutter:

  uses-material-design: true
