name: city_picker_example
description: Demonstrates how to use the city_pickers plugin.

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_city_picker:
    path: ../
  provider: ^5.0.0
  flutter_colorpicker: ^0.4.0

flutter:

  uses-material-design: true
