name: flutter_city_picker
description: Flutter plugin for city picker, Address picker, Popups widgets, call by function.
version: 2.0.1
homepage: https://github.com/wenchaosong/FlutterCityPicker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
