name: flutter_city_picker
description:  Flutter plugin for city picker,  Popups widgets, call by function,  support china.
version: 0.0.1
homepage: https://github.com/wenchaosong/CityPicker

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/lpinyin
  lpinyin: ^1.1.1
